### ISSUE TITLE
Граници на градове и селa

### ISSUE THREAD

**Issue by yurukov** [yurukov/Bulgaria-geocoding#1]
В последния месец се опитвам да намеря от къде да взема границите на населените места. Имам координатите на всички вече. Интересно ще е да се намерят границите и дори землищата им, ако са формално дефинирани.

Пробвах да ги изведа от openstreet maps. Там има relation-и, които са отбелязани като residential и като източник е посочен "Agenţia Europeană de Mediu, CORINE Land Cover, 2006". Не мисля, че покриват целите градове обаче. После проверих тези с place=[city,town,vilage] и ми излязоха само 49 граници - останалото бяха точки.

Някой има ли идея къде може да намерим всички граници на населени места?

**Comment by yurukov** [comment]
Хрумна ми, че може да използваме това тук:
http://gis.mrrb.government.bg/pmapper/map_separate-legend.phtml?winsize=medium&language=bg&config=separate-legend
Ако успеем да го изкараме в geojson format

**Comment by olannyv** [comment]
Здравей Боян,

Кажи ми твой личен мейл, да те свържа с човек, който може да помогне...

Даниел
(daniel.vladinov@gmail.com)

2014-10-22 15:00 GMT+03:00 Boyan Yurukov notifications@github.com:

**Comment by yurukov** [comment]
Заредих всички земплища и направих geojson с над 99% опростяване на геометрията. 
https://github.com/yurukov/Bulgaria-geocoding#settlementsgeojson
