### ISSUE TITLE
New Data Request

### ISSUE THREAD

**Issue by justinelliotmeyers** [yurukov/Bulgaria-geocoding#6]
hello! do you have access to a new dataset? I have an older version here: https://github.com/justinelliotmeyers/BULGARIA_2018_EKATTE however I am looking for something current to 2020.  Thanks!

**Comment by alvelchev** [comment]
Hello, at the moment we don't have a new dataset but we are working on it for the different regions in Bulgaria

**Comment by justinelliotmeyers** [comment]
@alvelchev Any update on the project?  Thank you!
